[package]
name = "code_assistant_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "code_assistant_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.2", features = ["extension-module"] }
walkdir = "2.5.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
tempfile = "3.8" 